name: example
description: Showcase Moon Design core widgets.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  moon_core:
    path: ../
dev_dependencies:
  custom_lint: ^0.7.6
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mix_lint: ^1.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
