name: moon_core
description: Moon Design System headless UI core widgets for Flutter.
version: 0.0.1
homepage: ''

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  mix: ^1.1.0
  mix_annotations: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  mix_generator: ^0.1.1

flutter:
  uses-material-design: true